//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb_Cinema.ServiceFunciones {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultFunciones", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema.Servicios")]
    [System.SerializableAttribute()]
    public partial class ResultFunciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb_Cinema.ServiceFunciones.ConsultFunciones_Result[] FuncionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb_Cinema.ServiceFunciones.ConsultFunciones_Result[] Funciones {
            get {
                return this.FuncionesField;
            }
            set {
                if ((object.ReferenceEquals(this.FuncionesField, value) != true)) {
                    this.FuncionesField = value;
                    this.RaisePropertyChanged("Funciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultFunciones_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema")]
    [System.SerializableAttribute()]
    public partial class ConsultFunciones_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal F_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string F_NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal F_PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal F_ID {
            get {
                return this.F_IDField;
            }
            set {
                if ((this.F_IDField.Equals(value) != true)) {
                    this.F_IDField = value;
                    this.RaisePropertyChanged("F_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string F_Nombre {
            get {
                return this.F_NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.F_NombreField, value) != true)) {
                    this.F_NombreField = value;
                    this.RaisePropertyChanged("F_Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal F_Precio {
            get {
                return this.F_PrecioField;
            }
            set {
                if ((this.F_PrecioField.Equals(value) != true)) {
                    this.F_PrecioField = value;
                    this.RaisePropertyChanged("F_Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoFuncionHora", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema.Servicios")]
    [System.SerializableAttribute()]
    public partial class InfoFuncionHora : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool DescuentoField;
        
        private string FechaField;
        
        private int FuncionField;
        
        private string HoraField;
        
        private int NumeroSillasField;
        
        private int PorcentajeDescuentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Descuento {
            get {
                return this.DescuentoField;
            }
            set {
                if ((this.DescuentoField.Equals(value) != true)) {
                    this.DescuentoField = value;
                    this.RaisePropertyChanged("Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Funcion {
            get {
                return this.FuncionField;
            }
            set {
                if ((this.FuncionField.Equals(value) != true)) {
                    this.FuncionField = value;
                    this.RaisePropertyChanged("Funcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroSillas {
            get {
                return this.NumeroSillasField;
            }
            set {
                if ((this.NumeroSillasField.Equals(value) != true)) {
                    this.NumeroSillasField = value;
                    this.RaisePropertyChanged("NumeroSillas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PorcentajeDescuento {
            get {
                return this.PorcentajeDescuentoField;
            }
            set {
                if ((this.PorcentajeDescuentoField.Equals(value) != true)) {
                    this.PorcentajeDescuentoField = value;
                    this.RaisePropertyChanged("PorcentajeDescuento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultFechas", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema.Servicios")]
    [System.SerializableAttribute()]
    public partial class ResultFechas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] FechasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Fechas {
            get {
                return this.FechasField;
            }
            set {
                if ((object.ReferenceEquals(this.FechasField, value) != true)) {
                    this.FechasField = value;
                    this.RaisePropertyChanged("Fechas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultHoras", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema.Servicios")]
    [System.SerializableAttribute()]
    public partial class ResultHoras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb_Cinema.ServiceFunciones.ConsultHorasFuncion_Result[] HorasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb_Cinema.ServiceFunciones.ConsultHorasFuncion_Result[] Horas {
            get {
                return this.HorasField;
            }
            set {
                if ((object.ReferenceEquals(this.HorasField, value) != true)) {
                    this.HorasField = value;
                    this.RaisePropertyChanged("Horas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultHorasFuncion_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema")]
    [System.SerializableAttribute()]
    public partial class ConsultHorasFuncion_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HF_DescuentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HF_HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal HF_PorcentajeDescuentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HF_Descuento {
            get {
                return this.HF_DescuentoField;
            }
            set {
                if ((this.HF_DescuentoField.Equals(value) != true)) {
                    this.HF_DescuentoField = value;
                    this.RaisePropertyChanged("HF_Descuento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HF_Hora {
            get {
                return this.HF_HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HF_HoraField, value) != true)) {
                    this.HF_HoraField = value;
                    this.RaisePropertyChanged("HF_Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal HF_PorcentajeDescuento {
            get {
                return this.HF_PorcentajeDescuentoField;
            }
            set {
                if ((this.HF_PorcentajeDescuentoField.Equals(value) != true)) {
                    this.HF_PorcentajeDescuentoField = value;
                    this.RaisePropertyChanged("HF_PorcentajeDescuento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultSillas", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema.Servicios")]
    [System.SerializableAttribute()]
    public partial class ResultSillas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb_Cinema.ServiceFunciones.ConsultSillasFuncion_Result[] SillasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb_Cinema.ServiceFunciones.ConsultSillasFuncion_Result[] Sillas {
            get {
                return this.SillasField;
            }
            set {
                if ((object.ReferenceEquals(this.SillasField, value) != true)) {
                    this.SillasField = value;
                    this.RaisePropertyChanged("Sillas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultSillasFuncion_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema")]
    [System.SerializableAttribute()]
    public partial class ConsultSillasFuncion_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FHS_ReservadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FHS_SillaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FHS_Reservada {
            get {
                return this.FHS_ReservadaField;
            }
            set {
                if ((this.FHS_ReservadaField.Equals(value) != true)) {
                    this.FHS_ReservadaField = value;
                    this.RaisePropertyChanged("FHS_Reservada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FHS_Silla {
            get {
                return this.FHS_SillaField;
            }
            set {
                if ((this.FHS_SillaField.Equals(value) != true)) {
                    this.FHS_SillaField = value;
                    this.RaisePropertyChanged("FHS_Silla");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceFunciones.IFunciones")]
    public interface IFunciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/CreateFuncion", ReplyAction="http://tempuri.org/IFunciones/CreateFuncionResponse")]
        string CreateFuncion(string nombre, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/CreateFuncion", ReplyAction="http://tempuri.org/IFunciones/CreateFuncionResponse")]
        System.Threading.Tasks.Task<string> CreateFuncionAsync(string nombre, int precio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/ConsultFunciones", ReplyAction="http://tempuri.org/IFunciones/ConsultFuncionesResponse")]
        AppWeb_Cinema.ServiceFunciones.ResultFunciones ConsultFunciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/ConsultFunciones", ReplyAction="http://tempuri.org/IFunciones/ConsultFuncionesResponse")]
        System.Threading.Tasks.Task<AppWeb_Cinema.ServiceFunciones.ResultFunciones> ConsultFuncionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/CreateHoraFuncion", ReplyAction="http://tempuri.org/IFunciones/CreateHoraFuncionResponse")]
        string CreateHoraFuncion(AppWeb_Cinema.ServiceFunciones.InfoFuncionHora data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/CreateHoraFuncion", ReplyAction="http://tempuri.org/IFunciones/CreateHoraFuncionResponse")]
        System.Threading.Tasks.Task<string> CreateHoraFuncionAsync(AppWeb_Cinema.ServiceFunciones.InfoFuncionHora data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/ConsultFechasFuncion", ReplyAction="http://tempuri.org/IFunciones/ConsultFechasFuncionResponse")]
        AppWeb_Cinema.ServiceFunciones.ResultFechas ConsultFechasFuncion(int funcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/ConsultFechasFuncion", ReplyAction="http://tempuri.org/IFunciones/ConsultFechasFuncionResponse")]
        System.Threading.Tasks.Task<AppWeb_Cinema.ServiceFunciones.ResultFechas> ConsultFechasFuncionAsync(int funcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/ConsultHorasFuncion", ReplyAction="http://tempuri.org/IFunciones/ConsultHorasFuncionResponse")]
        AppWeb_Cinema.ServiceFunciones.ResultHoras ConsultHorasFuncion(int funcion, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/ConsultHorasFuncion", ReplyAction="http://tempuri.org/IFunciones/ConsultHorasFuncionResponse")]
        System.Threading.Tasks.Task<AppWeb_Cinema.ServiceFunciones.ResultHoras> ConsultHorasFuncionAsync(int funcion, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/ConsultSillasFuncion", ReplyAction="http://tempuri.org/IFunciones/ConsultSillasFuncionResponse")]
        AppWeb_Cinema.ServiceFunciones.ResultSillas ConsultSillasFuncion(int funcion, string fecha, string hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFunciones/ConsultSillasFuncion", ReplyAction="http://tempuri.org/IFunciones/ConsultSillasFuncionResponse")]
        System.Threading.Tasks.Task<AppWeb_Cinema.ServiceFunciones.ResultSillas> ConsultSillasFuncionAsync(int funcion, string fecha, string hora);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFuncionesChannel : AppWeb_Cinema.ServiceFunciones.IFunciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FuncionesClient : System.ServiceModel.ClientBase<AppWeb_Cinema.ServiceFunciones.IFunciones>, AppWeb_Cinema.ServiceFunciones.IFunciones {
        
        public FuncionesClient() {
        }
        
        public FuncionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FuncionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FuncionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateFuncion(string nombre, int precio) {
            return base.Channel.CreateFuncion(nombre, precio);
        }
        
        public System.Threading.Tasks.Task<string> CreateFuncionAsync(string nombre, int precio) {
            return base.Channel.CreateFuncionAsync(nombre, precio);
        }
        
        public AppWeb_Cinema.ServiceFunciones.ResultFunciones ConsultFunciones() {
            return base.Channel.ConsultFunciones();
        }
        
        public System.Threading.Tasks.Task<AppWeb_Cinema.ServiceFunciones.ResultFunciones> ConsultFuncionesAsync() {
            return base.Channel.ConsultFuncionesAsync();
        }
        
        public string CreateHoraFuncion(AppWeb_Cinema.ServiceFunciones.InfoFuncionHora data) {
            return base.Channel.CreateHoraFuncion(data);
        }
        
        public System.Threading.Tasks.Task<string> CreateHoraFuncionAsync(AppWeb_Cinema.ServiceFunciones.InfoFuncionHora data) {
            return base.Channel.CreateHoraFuncionAsync(data);
        }
        
        public AppWeb_Cinema.ServiceFunciones.ResultFechas ConsultFechasFuncion(int funcion) {
            return base.Channel.ConsultFechasFuncion(funcion);
        }
        
        public System.Threading.Tasks.Task<AppWeb_Cinema.ServiceFunciones.ResultFechas> ConsultFechasFuncionAsync(int funcion) {
            return base.Channel.ConsultFechasFuncionAsync(funcion);
        }
        
        public AppWeb_Cinema.ServiceFunciones.ResultHoras ConsultHorasFuncion(int funcion, string fecha) {
            return base.Channel.ConsultHorasFuncion(funcion, fecha);
        }
        
        public System.Threading.Tasks.Task<AppWeb_Cinema.ServiceFunciones.ResultHoras> ConsultHorasFuncionAsync(int funcion, string fecha) {
            return base.Channel.ConsultHorasFuncionAsync(funcion, fecha);
        }
        
        public AppWeb_Cinema.ServiceFunciones.ResultSillas ConsultSillasFuncion(int funcion, string fecha, string hora) {
            return base.Channel.ConsultSillasFuncion(funcion, fecha, hora);
        }
        
        public System.Threading.Tasks.Task<AppWeb_Cinema.ServiceFunciones.ResultSillas> ConsultSillasFuncionAsync(int funcion, string fecha, string hora) {
            return base.Channel.ConsultSillasFuncionAsync(funcion, fecha, hora);
        }
    }
}
