//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb_Cinema.ServiceReservas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="infoReserva", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema.Servicios")]
    [System.SerializableAttribute()]
    public partial class infoReserva : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DocumentoField;
        
        private string FechaField;
        
        private int FuncionField;
        
        private string HoraField;
        
        private string NombreField;
        
        private int SillaField;
        
        private string TelefonoField;
        
        private int ValorPagaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaField, value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Funcion {
            get {
                return this.FuncionField;
            }
            set {
                if ((this.FuncionField.Equals(value) != true)) {
                    this.FuncionField = value;
                    this.RaisePropertyChanged("Funcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Hora {
            get {
                return this.HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.HoraField, value) != true)) {
                    this.HoraField = value;
                    this.RaisePropertyChanged("Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Silla {
            get {
                return this.SillaField;
            }
            set {
                if ((this.SillaField.Equals(value) != true)) {
                    this.SillaField = value;
                    this.RaisePropertyChanged("Silla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ValorPaga {
            get {
                return this.ValorPagaField;
            }
            set {
                if ((this.ValorPagaField.Equals(value) != true)) {
                    this.ValorPagaField = value;
                    this.RaisePropertyChanged("ValorPaga");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="resultReservasHora", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema.Servicios")]
    [System.SerializableAttribute()]
    public partial class resultReservasHora : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb_Cinema.ServiceReservas.ConsultReservasFuncionHora_Result[] ReservasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb_Cinema.ServiceReservas.ConsultReservasFuncionHora_Result[] Reservas {
            get {
                return this.ReservasField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservasField, value) != true)) {
                    this.ReservasField = value;
                    this.RaisePropertyChanged("Reservas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultReservasFuncionHora_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema")]
    [System.SerializableAttribute()]
    public partial class ConsultReservasFuncionHora_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string R_DocumentoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string R_FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string R_FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal R_Funcion_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string R_HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string R_NombrePersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal R_SillaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string R_TelefonoPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal R_ValorPagadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string R_DocumentoPersona {
            get {
                return this.R_DocumentoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.R_DocumentoPersonaField, value) != true)) {
                    this.R_DocumentoPersonaField = value;
                    this.RaisePropertyChanged("R_DocumentoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string R_Fecha {
            get {
                return this.R_FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.R_FechaField, value) != true)) {
                    this.R_FechaField = value;
                    this.RaisePropertyChanged("R_Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string R_FechaReserva {
            get {
                return this.R_FechaReservaField;
            }
            set {
                if ((object.ReferenceEquals(this.R_FechaReservaField, value) != true)) {
                    this.R_FechaReservaField = value;
                    this.RaisePropertyChanged("R_FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal R_Funcion_ID {
            get {
                return this.R_Funcion_IDField;
            }
            set {
                if ((this.R_Funcion_IDField.Equals(value) != true)) {
                    this.R_Funcion_IDField = value;
                    this.RaisePropertyChanged("R_Funcion_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string R_Hora {
            get {
                return this.R_HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.R_HoraField, value) != true)) {
                    this.R_HoraField = value;
                    this.RaisePropertyChanged("R_Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string R_NombrePersona {
            get {
                return this.R_NombrePersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.R_NombrePersonaField, value) != true)) {
                    this.R_NombrePersonaField = value;
                    this.RaisePropertyChanged("R_NombrePersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal R_Silla {
            get {
                return this.R_SillaField;
            }
            set {
                if ((this.R_SillaField.Equals(value) != true)) {
                    this.R_SillaField = value;
                    this.RaisePropertyChanged("R_Silla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string R_TelefonoPersona {
            get {
                return this.R_TelefonoPersonaField;
            }
            set {
                if ((object.ReferenceEquals(this.R_TelefonoPersonaField, value) != true)) {
                    this.R_TelefonoPersonaField = value;
                    this.RaisePropertyChanged("R_TelefonoPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal R_ValorPagado {
            get {
                return this.R_ValorPagadoField;
            }
            set {
                if ((this.R_ValorPagadoField.Equals(value) != true)) {
                    this.R_ValorPagadoField = value;
                    this.RaisePropertyChanged("R_ValorPagado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="resultReservas", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema.Servicios")]
    [System.SerializableAttribute()]
    public partial class resultReservas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AppWeb_Cinema.ServiceReservas.ConsultHorariosReservasFuncion_Result[] ReservasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((this.ErrorField.Equals(value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AppWeb_Cinema.ServiceReservas.ConsultHorariosReservasFuncion_Result[] Reservas {
            get {
                return this.ReservasField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservasField, value) != true)) {
                    this.ReservasField = value;
                    this.RaisePropertyChanged("Reservas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultHorariosReservasFuncion_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFCinema")]
    [System.SerializableAttribute()]
    public partial class ConsultHorariosReservasFuncion_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FHS_FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FHS_Funcion_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FHS_HoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalReservasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalSillasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FHS_Fecha {
            get {
                return this.FHS_FechaField;
            }
            set {
                if ((object.ReferenceEquals(this.FHS_FechaField, value) != true)) {
                    this.FHS_FechaField = value;
                    this.RaisePropertyChanged("FHS_Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FHS_Funcion_ID {
            get {
                return this.FHS_Funcion_IDField;
            }
            set {
                if ((this.FHS_Funcion_IDField.Equals(value) != true)) {
                    this.FHS_Funcion_IDField = value;
                    this.RaisePropertyChanged("FHS_Funcion_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FHS_Hora {
            get {
                return this.FHS_HoraField;
            }
            set {
                if ((object.ReferenceEquals(this.FHS_HoraField, value) != true)) {
                    this.FHS_HoraField = value;
                    this.RaisePropertyChanged("FHS_Hora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalReservas {
            get {
                return this.TotalReservasField;
            }
            set {
                if ((this.TotalReservasField.Equals(value) != true)) {
                    this.TotalReservasField = value;
                    this.RaisePropertyChanged("TotalReservas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalSillas {
            get {
                return this.TotalSillasField;
            }
            set {
                if ((this.TotalSillasField.Equals(value) != true)) {
                    this.TotalSillasField = value;
                    this.RaisePropertyChanged("TotalSillas");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReservas.IReservas")]
    public interface IReservas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservas/CreateReserva", ReplyAction="http://tempuri.org/IReservas/CreateReservaResponse")]
        string CreateReserva(AppWeb_Cinema.ServiceReservas.infoReserva data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservas/CreateReserva", ReplyAction="http://tempuri.org/IReservas/CreateReservaResponse")]
        System.Threading.Tasks.Task<string> CreateReservaAsync(AppWeb_Cinema.ServiceReservas.infoReserva data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservas/ConsultReservasFuncionHora", ReplyAction="http://tempuri.org/IReservas/ConsultReservasFuncionHoraResponse")]
        AppWeb_Cinema.ServiceReservas.resultReservasHora ConsultReservasFuncionHora(int funcion, string fecha, string hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservas/ConsultReservasFuncionHora", ReplyAction="http://tempuri.org/IReservas/ConsultReservasFuncionHoraResponse")]
        System.Threading.Tasks.Task<AppWeb_Cinema.ServiceReservas.resultReservasHora> ConsultReservasFuncionHoraAsync(int funcion, string fecha, string hora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservas/ConsultReservasFuncion", ReplyAction="http://tempuri.org/IReservas/ConsultReservasFuncionResponse")]
        AppWeb_Cinema.ServiceReservas.resultReservas ConsultReservasFuncion(int funcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservas/ConsultReservasFuncion", ReplyAction="http://tempuri.org/IReservas/ConsultReservasFuncionResponse")]
        System.Threading.Tasks.Task<AppWeb_Cinema.ServiceReservas.resultReservas> ConsultReservasFuncionAsync(int funcion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservasChannel : AppWeb_Cinema.ServiceReservas.IReservas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservasClient : System.ServiceModel.ClientBase<AppWeb_Cinema.ServiceReservas.IReservas>, AppWeb_Cinema.ServiceReservas.IReservas {
        
        public ReservasClient() {
        }
        
        public ReservasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateReserva(AppWeb_Cinema.ServiceReservas.infoReserva data) {
            return base.Channel.CreateReserva(data);
        }
        
        public System.Threading.Tasks.Task<string> CreateReservaAsync(AppWeb_Cinema.ServiceReservas.infoReserva data) {
            return base.Channel.CreateReservaAsync(data);
        }
        
        public AppWeb_Cinema.ServiceReservas.resultReservasHora ConsultReservasFuncionHora(int funcion, string fecha, string hora) {
            return base.Channel.ConsultReservasFuncionHora(funcion, fecha, hora);
        }
        
        public System.Threading.Tasks.Task<AppWeb_Cinema.ServiceReservas.resultReservasHora> ConsultReservasFuncionHoraAsync(int funcion, string fecha, string hora) {
            return base.Channel.ConsultReservasFuncionHoraAsync(funcion, fecha, hora);
        }
        
        public AppWeb_Cinema.ServiceReservas.resultReservas ConsultReservasFuncion(int funcion) {
            return base.Channel.ConsultReservasFuncion(funcion);
        }
        
        public System.Threading.Tasks.Task<AppWeb_Cinema.ServiceReservas.resultReservas> ConsultReservasFuncionAsync(int funcion) {
            return base.Channel.ConsultReservasFuncionAsync(funcion);
        }
    }
}
